# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_tool_widget.ui'
#
# Created: Sat Jun  6 14:38:11 2015
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CreateTool(object):
    def setupUi(self, CreateTool):
        CreateTool.setObjectName("CreateTool")
        CreateTool.resize(862, 632)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(CreateTool)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(CreateTool)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.edToolName = QtWidgets.QLineEdit(CreateTool)
        self.edToolName.setObjectName("edToolName")
        self.horizontalLayout_3.addWidget(self.edToolName)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.groupBox = QtWidgets.QGroupBox(CreateTool)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.cbIO = QtWidgets.QComboBox(self.groupBox)
        self.cbIO.setObjectName("cbIO")
        self.verticalLayout_2.addWidget(self.cbIO)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.edOptName = QtWidgets.QLineEdit(self.groupBox)
        self.edOptName.setObjectName("edOptName")
        self.verticalLayout_3.addWidget(self.edOptName)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.edOptType = QtWidgets.QLineEdit(self.groupBox)
        self.edOptType.setObjectName("edOptType")
        self.verticalLayout_4.addWidget(self.edOptType)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.edOptRepr = QtWidgets.QLineEdit(self.groupBox)
        self.edOptRepr.setObjectName("edOptRepr")
        self.verticalLayout_5.addWidget(self.edOptRepr)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.edOptDef = QtWidgets.QLineEdit(self.groupBox)
        self.edOptDef.setObjectName("edOptDef")
        self.verticalLayout_6.addWidget(self.edOptDef)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.btnAddOpt = QtWidgets.QPushButton(self.groupBox)
        self.btnAddOpt.setObjectName("btnAddOpt")
        self.verticalLayout_7.addWidget(self.btnAddOpt)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tblOptions = QtWidgets.QTableView(CreateTool)
        self.tblOptions.setObjectName("tblOptions")
        self.horizontalLayout.addWidget(self.tblOptions)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnRemoveOpt = QtWidgets.QPushButton(CreateTool)
        self.btnRemoveOpt.setObjectName("btnRemoveOpt")
        self.verticalLayout.addWidget(self.btnRemoveOpt)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(CreateTool)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.edFormat = QtWidgets.QLineEdit(CreateTool)
        self.edFormat.setObjectName("edFormat")
        self.horizontalLayout_4.addWidget(self.edFormat)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.btnSave = QtWidgets.QPushButton(CreateTool)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_5.addWidget(self.btnSave)
        self.btnExit = QtWidgets.QPushButton(CreateTool)
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout_5.addWidget(self.btnExit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)

        self.retranslateUi(CreateTool)
        QtCore.QMetaObject.connectSlotsByName(CreateTool)

    def retranslateUi(self, CreateTool):
        _translate = QtCore.QCoreApplication.translate
        CreateTool.setWindowTitle(_translate("CreateTool", "Create tool"))
        self.label.setText(_translate("CreateTool", "Tool name"))
        self.groupBox.setTitle(_translate("CreateTool", "New option"))
        self.label_3.setText(_translate("CreateTool", "IO"))
        self.label_4.setText(_translate("CreateTool", "name"))
        self.label_5.setText(_translate("CreateTool", "type"))
        self.label_6.setText(_translate("CreateTool", "format"))
        self.label_7.setText(_translate("CreateTool", "default"))
        self.btnAddOpt.setText(_translate("CreateTool", "Add option"))
        self.btnRemoveOpt.setText(_translate("CreateTool", "Remove"))
        self.label_2.setText(_translate("CreateTool", "Format"))
        self.btnSave.setText(_translate("CreateTool", "Save"))
        self.btnExit.setText(_translate("CreateTool", "Exit"))

