# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mian_window.ui'
#
# Created: Wed Jun  3 17:19:49 2015
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(836, 651)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbToolName = QtWidgets.QLabel(Form)
        self.lbToolName.setObjectName("lbToolName")
        self.horizontalLayout_3.addWidget(self.lbToolName)
        self.edToolName = QtWidgets.QLineEdit(Form)
        self.edToolName.setObjectName("edToolName")
        self.horizontalLayout_3.addWidget(self.edToolName)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.cbIO = QtWidgets.QComboBox(self.groupBox)
        self.cbIO.setEditable(False)
        self.cbIO.setObjectName("cbIO")
        self.verticalLayout_5.addWidget(self.cbIO)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.edOptName = QtWidgets.QLineEdit(self.groupBox)
        self.edOptName.setClearButtonEnabled(False)
        self.edOptName.setObjectName("edOptName")
        self.verticalLayout.addWidget(self.edOptName)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.edOptRepr = QtWidgets.QLineEdit(self.groupBox)
        self.edOptRepr.setObjectName("edOptRepr")
        self.verticalLayout_7.addWidget(self.edOptRepr)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.edOptType = QtWidgets.QLineEdit(self.groupBox)
        self.edOptType.setObjectName("edOptType")
        self.verticalLayout_2.addWidget(self.edOptType)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.edOptDef = QtWidgets.QLineEdit(self.groupBox)
        self.edOptDef.setObjectName("edOptDef")
        self.verticalLayout_3.addWidget(self.edOptDef)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.btnAddOpt = QtWidgets.QPushButton(self.groupBox)
        self.btnAddOpt.setObjectName("btnAddOpt")
        self.verticalLayout_4.addWidget(self.btnAddOpt)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_8.addWidget(self.groupBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tblOptions = QtWidgets.QTableView(Form)
        self.tblOptions.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblOptions.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblOptions.setObjectName("tblOptions")
        self.tblOptions.verticalHeader().setVisible(False)
        self.horizontalLayout_4.addWidget(self.tblOptions)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btnRemoveOpt = QtWidgets.QPushButton(Form)
        self.btnRemoveOpt.setObjectName("btnRemoveOpt")
        self.verticalLayout_6.addWidget(self.btnRemoveOpt)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.edFormat = QtWidgets.QLineEdit(Form)
        self.edFormat.setObjectName("edFormat")
        self.horizontalLayout_5.addWidget(self.edFormat)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnSave = QtWidgets.QPushButton(Form)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnExit = QtWidgets.QPushButton(Form)
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout.addWidget(self.btnExit)
        self.verticalLayout_8.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbToolName.setText(_translate("Form", "Tool name"))
        self.groupBox.setTitle(_translate("Form", "NewOption"))
        self.label.setText(_translate("Form", "name"))
        self.label_7.setText(_translate("Form", "repr"))
        self.label_2.setText(_translate("Form", "type"))
        self.label_3.setText(_translate("Form", "default"))
        self.btnAddOpt.setText(_translate("Form", "Add option"))
        self.btnRemoveOpt.setText(_translate("Form", "Remove"))
        self.label_6.setText(_translate("Form", "Format string"))
        self.btnSave.setText(_translate("Form", "Save"))
        self.btnExit.setText(_translate("Form", "Exit"))

